apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: keystore
  name: keystore
spec:
  replicas: 1
  selector:
    matchLabels:
      app: keystore
  template:
    metadata:
      labels:
        app: keystore
    spec:
      containers:
        - env:
            - name: GRPC_HOST
              value: 0.0.0.0
            - name: GRPC_PORT
              value: "50051"
            - name: MONGODB_DATABASE
              value: assets
          envFrom:
            - secretRef:
                name: keystore
          image: 667950714614.dkr.ecr.us-east-1.amazonaws.com/keystore-service:0.9.1
          imagePullPolicy: IfNotPresent
          livenessProbe:
            failureThreshold: 3
            initialDelaySeconds: 10
            periodSeconds: 10
            successThreshold: 1
            tcpSocket:
              port: 50051
            timeoutSeconds: 1
          name: keystore
          ports:
            - containerPort: 50051
              name: grpc
              protocol: TCP
