apiVersion: v1
kind: Service
metadata:
  labels:
    app: keystore
  name: keystore
spec:
  selector:
    app: keystore
  ports:
    - name: grpc
      port: 50051
      protocol: TCP
      targetPort: 50051
