apiVersion: v1
kind: Service
metadata:
  labels:
    app: keystore
  name: keystore
spec:
  ports:
    - name: grpc
      port: 50051
      targetPort: 50051
  selector:
    app: keystore
  type: LoadBalancer
