apiVersion: v1
kind: ReplicationController
metadata:
  name: keystore
spec:
  replicas: 1
  selector:
    app: keystore
  template:
    metadata:
      labels:
        app: keystore
    spec:
      containers:
        - name: keystore
          image: totem-gdn/keystore-service:latest # FIXME
          command:
            - "node dist/main.js"
          livenessProbe:
            grpc:
              port: 50051
            initialDelaySeconds: 10
          ports:
            - name: grpc
              containerPort: 50051
          env:
            - name: GRPC_HOST
            - name: GRPC_PORT
            - name: MONGODB_URI
            - name: MONGODB_DATABASE
